using Azure.Core;

namespace Anthropic.Foundry;

/// <summary>
/// Provides access to the azure foundry api though the usage of the environmental authentication generated by the <see cref="IAnthropicFoundryCredentials.FromEnv"/> method.
/// </summary>
public class AnthropicFoundryIdentityTokenCredentials : IAnthropicFoundryCredentials
{
    private readonly AccessToken _apiKey;

    /// <summary>
    /// Creates a new instance of the <see cref="AnthropicFoundryIdentityTokenCredentials"/> class.
    /// </summary>
    /// <param name="apiKey">The access token generated by the <see cref="IAnthropicFoundryCredentials.FromEnv"/> method.</param>
    /// <param name="resourceName">The resource name as part of the base url for the api.</param>
    public AnthropicFoundryIdentityTokenCredentials(AccessToken apiKey, string resourceName)
    {
        if (apiKey.Equals(default) || string.IsNullOrWhiteSpace(apiKey.Token))
        {
            throw new ArgumentNullException(nameof(apiKey), "Invalid/Empty api key struct is not valid");
        }
        _apiKey = apiKey;
        ResourceName = resourceName ?? throw new ArgumentNullException(nameof(resourceName));
    }

    public string ResourceName { get; }

    public void Apply(HttpRequestMessage requestMessage)
    {
        //TODO implement token refresh
        requestMessage.Headers.Authorization = new System.Net.Http.Headers.AuthenticationHeaderValue("bearer", _apiKey.Token);
    }
}
